### ISSUE TITLE
request to transfer hubot-bearychat adapter ownership

### ISSUE THREAD

**Issue by yuanbohan** [timnew/hubot-bearychat#1]
hi timenew,

@timnew , 我是 BearyChat 工程师，具体事宜已经给你发了邮件，还请查收一下。
再次感谢对 BearyChat 的信任和支持。

BearyChat 工程师
@yuanbohan

**Comment by wcp1231** [comment]
@yuanbohan 什么时候官方支持啊？

**Comment by yuanbohan** [comment]
@wcp1231 其实官方代码已经准备好了，希望 @timnew 能够转移一下 hubot-bearychat 的权限，我会将代码和教程上线。

**Comment by timnew** [comment]
```
[hubot-bearychat] npm unpublish                                                                                                                                                        1:31:42  ☁  master ☀
npm ERR! Refusing to delete entire project.
npm ERR! Run with --force to do this.
npm ERR! npm unpublish [<@scope>/]<pkg>[@<version>]
```

```
[hubot-bearychat] npm unpublish hubot-bearychat                                                                                                                                        1:31:53  ☁  master ☀
npm ERR! Refusing to delete entire project.
npm ERR! Run with --force to do this.
npm ERR! npm unpublish [<@scope>/]<pkg>[@<version>]
```

```
NPM-UNPUBLISH(1)                                                                                                                                                       NPM-UNPUBLISH(1)



NAME
       npm-unpublish - Remove a package from the registry

SYNOPSIS
         npm unpublish [<@scope>/]<pkg>[@<version>]

WARNING
       It is generally considered bad behavior to remove versions of a library that others are depending on!

       Consider using the deprecate command instead, if your intent is to encourage users to upgrade.

       There is plenty of room on the registry.

DESCRIPTION
       This removes a package version from the registry, deleting its entry and removing the tarball.

       If no version is specified, or if all versions are removed then the root package entry is removed from the registry entirely.

       Even  if  a package version is unpublished, that specific name and version combination can never be reused.  In order to publish the package again, a new version number must be
       used.

       The scope is optional and follows the usual rules for npm help 7 npm-scope.

SEE ALSO
       o npm help deprecate

       o npm help publish

       o npm help 7 registry

       o npm help adduser

       o npm help owner





                                                                                     November 2015                                                                     NPM-UNPUBLISH(1)
(END)
```

@yuanbohan 你确定要我这么干？“Even  if  a package version is unpublished, that specific name and version combination can never be reused”

**Comment by timnew** [comment]
```
[hubot-bearychat] npm publish hubot-bearychat --force                                                                                                                                  1:36:02  ☁  master ☀
npm WARN using --force I sure hope you know what you are doing.
npm ERR! publish Failed PUT 403
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "publish" "hubot-bearychat" "--force"
npm ERR! node v5.0.0
npm ERR! npm  v3.4.0
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 0.1.2." : hubot-bearychat
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/timnew/Workspace/hubot/hubot-bearychat/npm-debug.log
```

```
[hubot-bearychat] cat npm-debug.log                                                                                                                                                    1:36:16  ☁  master ☀
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish',
1 verbose cli   'hubot-bearychat',
1 verbose cli   '--force' ]
2 info using npm@3.4.0
3 info using node@v5.0.0
4 warn using --force I sure hope you know what you are doing.
5 verbose publish [ 'hubot-bearychat' ]
6 silly cache add args [ 'hubot-bearychat', null ]
7 verbose cache add spec hubot-bearychat
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'hubot-bearychat',
8 silly cache add   scope: null,
8 silly cache add   name: 'hubot-bearychat',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed hubot-bearychat@*
10 verbose addNamed "*" is a valid semver range for hubot-bearychat
11 silly addNameRange { name: 'hubot-bearychat', range: '*', hasData: false }
12 silly mapToRegistry name hubot-bearychat
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/hubot-bearychat
16 verbose addNameRange registry:https://registry.npmjs.org/hubot-bearychat not in flight; fetching
17 verbose request uri https://registry.npmjs.org/hubot-bearychat
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:36:13 AM
20 verbose request using bearer token for auth
21 verbose request id 731a309e0c431080
22 verbose etag "ZAUWDZL8PHRQ8FLL18SNGZTL"
23 http request GET https://registry.npmjs.org/hubot-bearychat
24 http 304 https://registry.npmjs.org/hubot-bearychat
25 verbose headers { 'cache-control': 'max-age=300',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Sun, 28 Feb 2016 17:36:13 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-lax1421-LAX',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1456680972.925609,VS0,VE170' }
26 silly get cb [ 304,
26 silly get   { 'cache-control': 'max-age=300',
26 silly get     'accept-ranges': 'bytes',
26 silly get     date: 'Sun, 28 Feb 2016 17:36:13 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-lax1421-LAX',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1456680972.925609,VS0,VE170' } ]
27 verbose etag https://registry.npmjs.org/hubot-bearychat from cache
28 verbose get saving hubot-bearychat to /Users/timnew/.npm/registry.npmjs.org/hubot-bearychat/.cache.json
29 silly addNameRange number 2 { name: 'hubot-bearychat', range: '*', hasData: true }
30 silly addNameRange versions [ 'hubot-bearychat', [ '0.1.0', '0.1.1', '0.1.2' ] ]
31 silly addNamed hubot-bearychat@0.1.2
32 verbose addNamed "0.1.2" is a plain semver version for hubot-bearychat
33 silly mapToRegistry name hubot-bearychat
34 silly mapToRegistry using default registry
35 silly mapToRegistry registry https://registry.npmjs.org/
36 silly mapToRegistry uri https://registry.npmjs.org/hubot-bearychat
37 verbose addRemoteTarball https://registry.npmjs.org/hubot-bearychat/-/hubot-bearychat-0.1.2.tgz not in flight; adding
38 verbose addRemoteTarball [ 'https://registry.npmjs.org/hubot-bearychat/-/hubot-bearychat-0.1.2.tgz',
38 verbose addRemoteTarball   '72a9792a1366b9a7ab57fd1745c4f063fda70248' ]
39 info retry fetch attempt 1 at 1:36:14 AM
40 info attempt registry request try #1 at 1:36:14 AM
41 http fetch GET https://registry.npmjs.org/hubot-bearychat/-/hubot-bearychat-0.1.2.tgz
42 verbose request using bearer token for auth
43 http fetch 200 https://registry.npmjs.org/hubot-bearychat/-/hubot-bearychat-0.1.2.tgz
44 silly fetchAndShaCheck shasum 72a9792a1366b9a7ab57fd1745c4f063fda70248
45 verbose addTmpTarball /var/folders/2s/_kxwf6ss2hv__pfsbtc741100000gq/T/npm-68605-ca32004c/registry.npmjs.org/hubot-bearychat/-/hubot-bearychat-0.1.2.tgz not in flight; adding
46 verbose addTmpTarball already have metadata; skipping unpack for hubot-bearychat@0.1.2
47 silly cache afterAdd hubot-bearychat@0.1.2
48 verbose afterAdd /Users/timnew/.npm/hubot-bearychat/0.1.2/package/package.json not in flight; writing
49 verbose afterAdd /Users/timnew/.npm/hubot-bearychat/0.1.2/package/package.json written
50 silly publish { name: 'hubot-bearychat',
50 silly publish   version: '0.1.2',
50 silly publish   description: 'Hubot Bearychat Adapter',
50 silly publish   main: './lib/bearychat',
50 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
50 silly publish   repository:
50 silly publish    { type: 'git',
50 silly publish      url: 'git+https://github.com/timnew/hubot-bearychat.git' },
50 silly publish   keywords: [ 'hubot', 'bearychat', 'adapter', 'channel' ],
50 silly publish   author: { name: 'TimNew' },
50 silly publish   license: 'MIT',
50 silly publish   bugs: { url: 'https://github.com/timnew/hubot-bearychat/issues' },
50 silly publish   homepage: 'https://github.com/timnew/hubot-bearychat#readme',
50 silly publish   peerDependencies: { hubot: '^2.17.0' },
50 silly publish   devDependencies: { 'coffee-script': '^1.10.0' },
50 silly publish   gitHead: '92196c6af350c8df11b69ef81f7795d60536cf9e',
50 silly publish   _id: 'hubot-bearychat@0.1.2',
50 silly publish   _shasum: '72a9792a1366b9a7ab57fd1745c4f063fda70248',
50 silly publish   _from: 'hubot-bearychat@*',
50 silly publish   _npmVersion: '3.4.0',
50 silly publish   _nodeVersion: '5.0.0',
50 silly publish   _npmUser: { name: 'timnew', email: 'timnew.wti@gmail.com' },
50 silly publish   dist:
50 silly publish    { shasum: '72a9792a1366b9a7ab57fd1745c4f063fda70248',
50 silly publish      tarball: 'http://registry.npmjs.org/hubot-bearychat/-/hubot-bearychat-0.1.2.tgz' },
50 silly publish   maintainers: [ { name: 'timnew', email: 'timnew.wti@gmail.com' } ],
50 silly publish   directories: {},
50 silly publish   _resolved: 'https://registry.npmjs.org/hubot-bearychat/-/hubot-bearychat-0.1.2.tgz' }
51 info lifecycle hubot-bearychat@0.1.2~prepublish: hubot-bearychat@0.1.2
52 silly lifecycle hubot-bearychat@0.1.2~prepublish: no script for prepublish, continuing
53 verbose getPublishConfig undefined
54 silly mapToRegistry name hubot-bearychat
55 silly mapToRegistry using default registry
56 silly mapToRegistry registry https://registry.npmjs.org/
57 silly mapToRegistry uri https://registry.npmjs.org/hubot-bearychat
58 verbose publish registryBase https://registry.npmjs.org/
59 silly publish uploading /Users/timnew/.npm/hubot-bearychat/0.1.2/package.tgz
60 verbose request uri https://registry.npmjs.org/hubot-bearychat
61 verbose request sending authorization for write operation
62 info attempt registry request try #1 at 1:36:15 AM
63 verbose request using bearer token for auth
64 http request PUT https://registry.npmjs.org/hubot-bearychat
65 http 403 https://registry.npmjs.org/hubot-bearychat
66 verbose headers { 'content-type': 'application/json',
66 verbose headers   'cache-control': 'max-age=300',
66 verbose headers   'content-length': '95',
66 verbose headers   'accept-ranges': 'bytes',
66 verbose headers   date: 'Sun, 28 Feb 2016 17:36:14 GMT',
66 verbose headers   via: '1.1 varnish',
66 verbose headers   connection: 'keep-alive',
66 verbose headers   'x-served-by': 'cache-lax1434-LAX',
66 verbose headers   'x-cache': 'MISS',
66 verbose headers   'x-cache-hits': '0',
66 verbose headers   'x-timer': 'S1456680974.628600,VS0,VE218' }
67 verbose request invalidating /Users/timnew/.npm/registry.npmjs.org/hubot-bearychat on PUT
68 error publish Failed PUT 403
69 verbose stack Error: "You cannot publish over the previously published version 0.1.2." : hubot-bearychat
69 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
69 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
69 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
69 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
69 verbose stack     at emitTwo (events.js:87:13)
69 verbose stack     at Request.emit (events.js:172:7)
69 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1082:10)
69 verbose stack     at emitOne (events.js:82:20)
69 verbose stack     at Request.emit (events.js:169:7)
69 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
70 verbose statusCode 403
71 verbose pkgid hubot-bearychat
72 verbose cwd /Users/timnew/Workspace/hubot/hubot-bearychat
73 error Darwin 15.3.0
74 error argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "publish" "hubot-bearychat" "--force"
75 error node v5.0.0
76 error npm  v3.4.0
77 error code E403
78 error "You cannot publish over the previously published version 0.1.2." : hubot-bearychat
79 error If you need help, you may report this error at:
79 error     <https://github.com/npm/npm/issues>
80 verbose exit [ 1, true ]
```

**Comment by timnew** [comment]
@yuanbohan 确定这么unpublish大丈夫？从doc和log来看，unpublish不是干这事情的啊～

你确定我unpublish了这个package你能重用？？？？？！！！！！

PS：从官方推荐的角度来说，似乎是建议用一个新的package。。。

**Comment by yuanbohan** [comment]
hi @timnew 你有什么建议么？ 目前我用的是 hubot-beary，或者你在 hubot-bearychat 中加下 Collaborators？ yuanbohan

**Comment by yuanbohan** [comment]
我试过，自己提一个 project， 在 npmjs 里可以看得到，然后我 unpublish --force 之后，刚开始还是有的，但是过了一会儿就看不到这个 project 了，应该有一些延迟。
我个人理解，这样的话就可以使用这个名字了。

**Comment by yuanbohan** [comment]
![_2016-02-24_11 3a11](https://cloud.githubusercontent.com/assets/4557527/13384640/88acb324-ded2-11e5-8f63-9aa4a81aa4e6.png)
![_2016-02-24_11 3a13](https://cloud.githubusercontent.com/assets/4557527/13384639/88ac0000-ded2-11e5-9387-6e55db9b6c67.png)

本地的效果，已经准备好了

**Comment by yuanbohan** [comment]
@timnew 可以把 yuanbohan 加入 collaborator 然后再把自己踢出么？ hubot 的上线就在这两天了，还希望能够支持一下，麻烦了。 我会将你的个人信息放到 bearychat 的 contributor 中

**Comment by timnew** [comment]
Done

**Comment by yuanbohan** [comment]
Thanks a lot

**Comment by ELLIEbleu** [comment]
@yuanbohan  bearychat sometimes occur "ERROR ReferenceError EventClosed is not defined"
Do you know this reason?

**Comment by timnew** [comment]
@ELLIEbleu this is a deprecated repo, please go to the official one

**Comment by ELLIEbleu** [comment]
@timnew  I use official bearychat ,I install on windows ，use a command "npm install hubot-bearychat --save" . when I run bearychat，sometimes occur "ERROR ReferenceError EventClosed is not defined"

**Comment by timnew** [comment]
@ELLIEbleu I mean I'm not maintaining the this package and updates. All stuff had handed over back to bearychat. Try contact @yuanbohan for more information.

**Comment by ELLIEbleu** [comment]
@yuanbohan  I use official bearychat ,I install on windows ，use a command "npm install hubot-bearychat --save" . when I run bearychat，sometimes occur "ERROR ReferenceError EventClosed is not defined" , I don't known why occur this  problem.
